version: '2'
services:
  openmoms-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/OpenMOMS/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=OpenMOMS
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
